#!/usr/bin/env python

import sys
import parserGenerator.grammarParser as gp

infile = ""
outfile = "out.gram"

if len(sys.argv) == 1:
    exit(1)

if len(sys.argv) == 3:
    exit(1)

if len(sys.argv) > 4:
    exit(1)

if len(sys.argv) == 2:
    infile = sys.argv[1]
else:
    if sys.argv[1] == "-o" or sys.argv[1] == "--output":
        outfile = sys.argv[2]
        infile = sys.argv[3]
    else:
        infile = sys.argv[1]
        if sys.argv[2] != "-o" and sys.argv[2] != "--output":
            exit(1)
        outfile = sys.argv[3]

rules, stateTable = gp.readDotGram(gp.grammarGramFile())
gp.save_grammar_to_file(infile, outfile, rules, stateTable)
